producer:
 properties:
  bootstrap_servers_config: localhost:9092
  acks_config: ALL
  retries_config: 0
  value_serializer_class_config: serializer.TransferSerializer
  key_serializer_class_config: org.apache.kafka.common.serialization.StringSerializer
  topic: transfers
server:
  port: 8081
  contextPath: /transfers