server:
  port: 9500

kafka:
  bootstrap-servers: localhost:9092
  topic:
    transactionQueue: transactionQueue

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: Ineegeerei1
  driver-class-name: org.postgresql.Driver
 jpa:
  generate-ddl: true

