server:
  port: 9500

kafka:
  bootstrap-servers: 10.10.1.12:9092
  topic:
    transactionQueue: transactionQueue

spring:
 datasource:
  url: jdbc:postgresql://localhost:5433/eight
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
 jpa:
  generate-ddl: true