consumer:
 properties:
  bootstrap_servers_config: localhost:9092
  group_id_config: transfersGroup
  auto_offset_reset_config: earliest
  value_deserializer_class_config: deserializer.TransferDeserializer
  key_deserializer_class_config: org.apache.kafka.common.serialization.StringDeserializer
  topic: transfers
externalBank:
 url: http://int.eight.inside.esiag.info:9191/externalBank/submit/
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver
  spring.jpa.generate-ddl: true