server:
  port: 8082
  contextPath: /fraudulent
spring:
 datasource:
  url: jdbc:postgresql://10.10.1.5:5432/eight
  username: eight
  password: eight
  driver-class-name: org.postgresql.Driver
 jpa:
  generate-ddl: true