producer:
 properties:
  bootstrap_servers_config: 192.168.20.4:9092
  acks_config: ALL
  retries_config: 0
  value_serializer_class_config: serializer.TransferSerializer
  key_serializer_class_config: org.apache.kafka.common.serialization.StringSerializer
  topic: transfers
server:
  port: 8081
  contextPath: /transfers
spring:
 datasource:
  url: jdbc:postgresql://localhost:5433/eight
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
 jpa:
  generate-ddl: true