consumer:
 properties:
  bootstrap_servers_config: 10.10.1.12:9092
  group_id_config: twitterGroup
  auto_offset_reset_config: earliest
  value_deserializer_class_config: org.apache.kafka.common.serialization.StringDeserializer
  key_deserializer_class_config: org.apache.kafka.common.serialization.LongDeserializer
  topic: tweets
spring :
  data :
    mongodb :
      host : 10.10.1.202
      port : 27017
      database : transfers