consumer:
 properties:
  bootstrap_servers_config: 10.10.1.101:9092
  group_id_config: approuvedGroup
  auto_offset_reset_config: latest
  topic: transactionApproved
producer:
 properties:
  bootstrap_servers_config: 10.10.1.101:9092
  topic: transactionApproved
server:
  port: 9005
  contextPath: /
spring:
 datasource:
  url: jdbc:postgresql://10.10.1.5:5432/eight
  username: eight
  password: eight
  driver-class-name: org.postgresql.Driver
 jpa:
  generate-ddl: true